name: cli_shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
  objectbox_generator: any
  test: ^1.24.0
dependencies:
  uuid: ^4.5.1
  equatable: ^2.0.5
