name: client_repositories
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.2.2
  shared: 
    path: '../shared'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
